theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
idle-timeout = 0	
completion-trigger-len = 4	
true-color = true	
color-modes	= true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"


[editor.lsp]
display-messages = true
auto-signature-help = true	
display-signature-help-docs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'


